### ISSUE TITLE
remove obsolete /etc/fstab entries

### ISSUE THREAD

**Issue by lueck-b** [bablokb/autobackup-service#1]
commit message for c26d410f9b6a7eea795a3059d7b9c05a7b208e19 reads:

changed mount-poit to /tmp/autobackup (entry in /etc/fstab no longer necessary)

But /etc/fstab is still mentioned in two files:

~$ wcgrep fstab autobackup-service-master/
autobackup-service-master/files/etc/autobackup.conf:11:# label of backup partition (you also need an entry in /etc/fstab for this)
autobackup-service-master/tools/install:87:echo "[INFO] Please edit /etc/autobackup.conf, /etc/rsnapshot.conf, /etc/fstab"

**Comment by bablokb** [comment]
thanks, fixed with [https://github.com/bablokb/autobackup-service/commit/5a3894b9e948ad1f313adbe0dc3dfb4389c900d5](https://github.com/bablokb/autobackup-service/commit/5a3894b9e948ad1f313adbe0dc3dfb4389c900d5)
