### ISSUE TITLE
automount needs to be disable for this to work

### ISSUE THREAD

**Issue by dfcsoftware** [bablokb/autobackup-service#2]
I could not get this to work until I disabled automount for gnome, like so:

<pre>
$ gsettings get org.gnome.desktop.media-handling automount
true
$ gsettings set org.gnome.desktop.media-handling automount false
$ gsettings get org.gnome.desktop.media-handling automount
false
$ gsettings set org.gnome.desktop.media-handling automount-open false
$ gsettings get org.gnome.desktop.media-handling automount-open
false 
</pre>

Perhaps you could add a note to the readme.md?

After doing this, it works perfectly!

Thanks for providing this very useful tool.
- Don

**Comment by bablokb** [comment]
Thanks for the contribution. I added a section in the readme and a file tools/gnome-disable-automount, see b093e80fb4292928a05565d2ad17b1ea3dd1a8b4.
Could you please check if  there is a copy&paste error? I also assumed the license is GPL3. If you like, I can also add your email to the file-header.

Bernhard

**Comment by dfcsoftware** [comment]
It looks and works perfectly. Thanks for the quick attention, and also the excellent article in Linux Magazine.

No need to add my email to the file-header, name is good enough as well as GPL3.

Regards,

-- Don
